apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-1yeq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-1yeq
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-1yeq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-1yeq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-1yeq
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xlxb-tenant/rhtap-demo-app/hacbs-test-project-1yeq@sha256:08f42e29c8190d39761e02507c6763a8eab26a851737a4903942961270921521
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
