apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-1yeq
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xlxb-tenant/rhtap-demo-app/hacbs-test-project-1yeq@sha256:6650e9b46cc547f9fdc6943f2d8ef01df7ae078bd17cc9cc28d7466cbcf4e770
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
